<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  left7:
    roles:
      - server
      - left7
      - agent
      - libreswan
      - default
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
  right7:
    roles:
      - server
      - right7
      - agent
      - libreswan
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
