---
HOSTS:
  left8:
    roles:
    - server
    - left8
    - agent
    - libreswan
    - default
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
  right8:
    roles:
    - server
    - right8
    - agent
    - libreswan
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
  left7:
    roles:
    - server
    - left7
    - agent
    - libreswan
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  right7:
    roles:
    - server
    - right7
    - agent
    - libreswan
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
